export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL";
export const SEARCH_COUNTRIES = "SEARCH_COUNTRIES";
export const FILTER_ALL_MY_COUNTRIES = "FILTER_ALL_MY_COUNTRIES";
export const WAY_TO_ORDER_COUNTRIES = "WAY_TO_ORDER_COUNTRIES";

export const ORDER_PER_ACTIVITY = "ORDER_PER_ACTIVITY"; // !

// =================  ACTIVITIES ==========================

export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES";
export const ADD_COUNTRY_ACTIVITY = "ADD_COUNTRY_ACTIVITY"; //!
// export const DELETE_COUNTRY_ACTIVITY = "DELETE_COUNTRY_ACTIVITY"; //!
export const FILTER_BY_ACTIVITIES = "FILTER_BY_ACTIVITIES";